#!/bin/sh
HERE=$(pwd)
echo $HERE

#################
# parse command line arguments
while echo $1 | grep ^- > /dev/null; do
    eval $( echo $1 | sed 's/-//g' | tr -d '\012')=$2
    shift
    shift
done

# set default values
if [ ! -n "$boost" ] # not is set
then 
    boost="true"
fi

#################
# 1) build boost libraries separately

if [ "$boost" = "true" ]
then
    echo 'Building boost libraries'    
    echo 'you can turn this of with argument "-boost false"'
    
    cd ../../boost_1_55_0
    rm ./project-config.jam*  # clean up from previous runs
    ./bootstrap.sh --with-libraries=system,filesystem,regex,thread,date_time,program_options,math
    ./b2
    
else
    echo 'not building boost libraries'
fi

#################
# 2) collect some information that can be used in source
cd $HERE
cd ../../help
HELP=$(pwd)

cd $HERE
cd ../../src/ui
echo "/* This file is automatically generated at installation by regenerate.sh script */\n" > constants.h
echo "static const char* INSTALL_DIR = \"$HERE\";" >> constants.h
echo "static const char* HELP_DIR = \"$HELP\";" >> constants.h


cd ../revlanguage
echo "/* This file is automatically generated at installation by regenerate.sh script */\n" > constants.h
echo "static const char* INSTALL_DIR = \"$HERE\";" >> constants.h
echo "static const char* HELP_DIR = \"$HELP\";" >> constants.h


#################
# 3) generate cmake configuration
cd $HERE
cd ../../src

echo 'generating revBayes build files'

# 1. CMakeLists.txt
echo 'cmake_minimum_required(VERSION 2.6)
project(RevBayes)

# Consider:
# -Wno-sign-compare
# -D_GLIBCXX_DEBUG

# Default compiler flags
if (WIN32)
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -O3 -Wall -g -pg -static -msse -msse2 -msse3")
    set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -O3 -g -Wall -pg -static")
else ()
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -O3 -Wall -g -pg -msse -msse2 -msse3")
    set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -O3 -g -Wall -pg")
endif ()

# Add extra CMake libraries into ./CMake
set(CMAKE_MODULE_PATH ${CMAKE_SOURCE_DIR}/CMake ${CMAKE_MODULE_PATH})

# Set source root relate to project file
set(PROJECT_SOURCE_DIR ${CMAKE_SOURCE_DIR}/../../src)

# TODO Split these up based on sub-package dependency
include_directories(' > "$HERE/CMakeLists.txt"
find ui libs core revlanguage -type d | grep -v "svn" | sed 's|^|    ${PROJECT_SOURCE_DIR}/|g' >> "$HERE/CMakeLists.txt"
echo ')

# Split into much smaller libraries
add_subdirectory(ui)
add_subdirectory(libs)
add_subdirectory(core)   
add_subdirectory(revlanguage)



############# executables #################
# basic rev-bayes binary
add_executable(rb ${PROJECT_SOURCE_DIR}/revlanguage/main.cpp)
target_link_libraries(rb rb-parser rb-core )

# extended rev-bayes binary
add_executable(rb-extended ${PROJECT_SOURCE_DIR}/ui/main.cpp)
target_link_libraries(rb-extended rb-ui rb-parser rb-core libs boost_system boost_filesystem boost_regex boost_thread boost_date_time boost_program_options boost_math_c99 boost_math_c99f boost_math_tr1f boost_math_tr1l)

# utility for generating help html files.
add_executable(help-html-generator ${PROJECT_SOURCE_DIR}/ui/HelpHtmlGenerator.cpp)
target_link_libraries(help-html-generator rb-parser rb-core libs boost_filesystem boost_system boost_regex)



########## boost section ##############

add_library(boost_system SHARED IMPORTED)
set_target_properties(boost_system PROPERTIES IMPORTED_LOCATION "../../boost_1_55_0/stage/lib/libboost_system.a")
           
add_library(boost_filesystem SHARED IMPORTED)
set_target_properties(boost_filesystem PROPERTIES IMPORTED_LOCATION "../../boost_1_55_0/stage/lib/libboost_filesystem.a")

add_library(boost_regex SHARED IMPORTED)
set_target_properties(boost_regex PROPERTIES IMPORTED_LOCATION "../../boost_1_55_0/stage/lib/libboost_regex.a")

add_library(boost_thread SHARED IMPORTED)
set_target_properties(boost_thread PROPERTIES IMPORTED_LOCATION "../../boost_1_55_0/stage/lib/libboost_thread.a")

add_library(boost_date_time SHARED IMPORTED)
set_target_properties(boost_date_time PROPERTIES IMPORTED_LOCATION "../../boost_1_55_0/stage/lib/libboost_date_time.a")

add_library(boost_program_options SHARED IMPORTED)
set_target_properties(boost_program_options PROPERTIES IMPORTED_LOCATION "../../boost_1_55_0/stage/lib/libboost_program_options.a")

add_library(boost_math_c99 SHARED IMPORTED)
set_target_properties(boost_math_c99 PROPERTIES IMPORTED_LOCATION "../../boost_1_55_0/stage/lib/libboost_math_c99.a")

add_library(boost_math_c99f SHARED IMPORTED)
set_target_properties(boost_math_c99f PROPERTIES IMPORTED_LOCATION "../../boost_1_55_0/stage/lib/libboost_math_c99f.a")

add_library(boost_math_tr1f SHARED IMPORTED)
set_target_properties(boost_math_tr1f PROPERTIES IMPORTED_LOCATION "../../boost_1_55_0/stage/lib/libboost_math_tr1f.a")

add_library(boost_math_tr1l SHARED IMPORTED)
set_target_properties(boost_math_tr1l PROPERTIES IMPORTED_LOCATION "../../boost_1_55_0/stage/lib/libboost_math_tr1l.a")


######## end of boost #################

######## optional bio++ ###############

SET(WITH_BPP)

#here is a useful function:
MACRO(IMPROVED_FIND_LIBRARY OUTPUT_LIBS lib_name include_to_find)
  #start:
  FIND_PATH(${lib_name}_INCLUDE_DIR ${include_to_find})
  SET(${lib_name}_NAMES ${lib_name} ${lib_name}lib ${lib_name}dll)
  FIND_LIBRARY(${lib_name}_LIBRARY NAMES ${${lib_name}_NAMES} PATH_SUFFIXES lib${LIB_SUFFIX})

  IF(${lib_name}_LIBRARY)
    MESSAGE("-- Library ${lib_name} found here:")
    MESSAGE("   includes : ${${lib_name}_INCLUDE_DIR}")
    MESSAGE("   libraries: ${${lib_name}_LIBRARY}")
  ELSE(${lib_name}_LIBRARY)
    MESSAGE("${lib_name} required but not found.")
    UNSET(WITH_BPP)
  ENDIF(${lib_name}_LIBRARY)
  
  #add the dependency:
  INCLUDE_DIRECTORIES(${${lib_name}_INCLUDE_DIR})
  SET(${OUTPUT_LIBS} ${${OUTPUT_LIBS}} ${${lib_name}_LIBRARY})
ENDMACRO(IMPROVED_FIND_LIBRARY)

#Find the Bio++ libraries:
IMPROVED_FIND_LIBRARY(LIBS bpp-core Bpp/Clonable.h)
IMPROVED_FIND_LIBRARY(LIBS bpp-seq Bpp/Seq/Alphabet/Alphabet.h)
IMPROVED_FIND_LIBRARY(LIBS bpp-phyl Bpp/Phyl/Tree.h)

# Subdirectories


# IF (DWITH_BPP)
#  SET(bpp-lib bpp-core bpp-seq bpp-phyl)
#  
#  FOREACH(bpplib ${bpp-lib})
#      find_library(${bpplib} SHARED ${BPPDIR})
#      set_target_properties(${bpplib} PROPERTIES LINKER_LANGUAGE CXX)
#      MESSAGE(${bpplib})
#  ENDFOREACH(bpplib)
# 
# 
#  #ADD_SUBDIRECTORY(bpp)
# ENDIF(DEFINED ${BPPDIR}) 
# 

' >> $HERE/CMakeLists.txt

echo

if [ ! -d "$HERE/ui" ]; then
mkdir "$HERE/ui"
fi
echo 'set(UI_FILES' > "$HERE/ui/CMakeLists.txt"
find ui | grep -v "svn" | sed 's|^|${PROJECT_SOURCE_DIR}/|g' >> "$HERE/ui/CMakeLists.txt"
echo ')
add_library(rb-ui ${UI_FILES})'  >> "$HERE/ui/CMakeLists.txt"

if [ ! -d "$HERE/libs" ]; then
mkdir "$HERE/libs"
fi
echo 'set(LIBS_FILES' > "$HERE/libs/CMakeLists.txt"
find libs | grep -v "svn" | sed 's|^|${PROJECT_SOURCE_DIR}/|g' >> "$HERE/libs/CMakeLists.txt"
echo ')
add_library(libs ${LIBS_FILES})'  >> "$HERE/libs/CMakeLists.txt"


if [ ! -d "$HERE/core" ]; then
mkdir "$HERE/core"
fi
echo 'set(CORE_FILES' > "$HERE/core/CMakeLists.txt"
find core | grep -v "svn" | sed 's|^|${PROJECT_SOURCE_DIR}/|g' >> "$HERE/core/CMakeLists.txt"
echo ')
add_library(rb-core ${CORE_FILES})'  >> "$HERE/core/CMakeLists.txt"


if [ ! -d "$HERE/revlanguage" ]; then
mkdir "$HERE/revlanguage"
fi
echo 'set(PARSER_FILES' > "$HERE/revlanguage/CMakeLists.txt"
find revlanguage | grep -v "svn" | sed 's|^|${PROJECT_SOURCE_DIR}/|g' >> "$HERE/revlanguage/CMakeLists.txt"
echo ')
add_library(rb-parser ${PARSER_FILES})'  >> "$HERE/revlanguage/CMakeLists.txt"


