/**
 * @file Lexical scanner generated by flex version 33
 * 
 * @note File hand-edited to remove gcc warnings about type casts
 *
 * @note Do not generate lexical scanner with version 35 of flex,
 *       it apparently has a bug in it that causes the parser to
 *       end up in an infinite loop.
 */


#line 2 "lex.yy.cpp"

#line 4 "lex.yy.cpp"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 33
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;
#endif /* ! C99 */

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

#define YY_LESS_LINENO(n)

/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
do \
{ \
/* Undo effects of setting up yytext. */ \
int yyless_macro_arg = (n); \
YY_LESS_LINENO(yyless_macro_arg);\
*yy_cp = (yy_hold_char); \
YY_RESTORE_YY_MORE_OFFSET \
(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
YY_DO_BEFORE_ACTION; /* set up yytext again */ \
} \
while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef unsigned int yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
{
	FILE *yy_input_file;
    
	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */
    
	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;
    
	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;
    
	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;
    
	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;
    
	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;
    
    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;
    
	int yy_buffer_status;
    
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
    
};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
? (yy_buffer_stack)[(yy_buffer_stack_top)] \
: NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,int len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
{ \
if ( ! YY_CURRENT_BUFFER ){ \
yyensure_buffer_stack (); \
YY_CURRENT_BUFFER_LVALUE =    \
yy_create_buffer(yyin,YY_BUF_SIZE ); \
} \
YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
}

#define yy_set_bol(at_bol) \
{ \
if ( ! YY_CURRENT_BUFFER ){\
yyensure_buffer_stack (); \
YY_CURRENT_BUFFER_LVALUE =    \
yy_create_buffer(yyin,YY_BUF_SIZE ); \
} \
YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
(yytext_ptr) = yy_bp; \
yyleng = (int) (yy_cp - yy_bp); \
(yy_hold_char) = *yy_cp; \
*yy_cp = '\0'; \
(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 41
#define YY_END_OF_BUFFER 42
/* This struct is not used in this scanner,
 but its presence is necessary. */
struct yy_trans_info
{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
};
static yyconst flex_int16_t yy_accept[118] =
{   0,
    0,    0,   42,   40,   38,   39,   40,   40,   23,   28,
    40,   40,   20,   40,   34,   27,   32,   21,   21,   21,
    21,   21,   21,   21,   21,   21,   21,   21,   21,   21,
    29,   26,   38,   37,    0,   22,   23,   30,    0,   20,
    18,   17,    0,   25,   24,   35,   36,   33,   21,   21,
    21,   21,   21,   21,   21,   21,   21,   21,    5,    4,
    21,   21,   21,   21,   21,   31,    0,   17,    0,    0,
    19,   21,   21,   21,   21,   21,   21,   21,    3,   21,
    21,   21,   21,   21,   21,    0,   18,    0,    0,   17,
    21,   14,   16,   21,   21,    6,   21,   21,    8,   11,
    
    21,   13,   21,    0,   17,   15,    9,    2,   12,   21,
    21,    7,   21,   10,   21,    1,    0
} ;

static yyconst flex_int32_t yy_ec[256] =
{   0,
    1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
    1,    2,    4,    5,    6,    1,    1,    7,    1,    1,
    1,    1,    8,    1,    9,   10,    1,   11,   11,   11,
    11,   11,   11,   11,   11,   11,   11,   12,    1,   13,
    14,   15,    1,    1,   16,   17,   17,   17,   18,   19,
    17,   17,   17,   17,   17,   20,   17,   21,   17,   17,
    17,   22,   23,   24,   25,   17,   17,   17,   17,   17,
    1,    1,    1,    1,   26,    1,   27,   28,   29,   17,
    
    30,   31,   17,   32,   33,   17,   34,   35,   17,   36,
    37,   17,   17,   38,   39,   40,   41,   17,   42,   43,
    17,   17,    1,   44,    1,   45,    1,    1,    1,    1,
    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
    
    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
    1,    1,    1,    1,    1
} ;

static yyconst flex_int32_t yy_meta[46] =
{   0,
    1,    1,    2,    1,    1,    1,    1,    1,    3,    1,
    3,    1,    1,    1,    1,    3,    3,    3,    3,    3,
    3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
    3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
    3,    3,    3,    1,    1
} ;

static yyconst flex_int16_t yy_base[121] =
{   0,
    0,    0,  159,  160,  156,  160,  143,  151,    0,  148,
    36,  143,   38,  139,   41,  138,  137,    0,  134,  124,
    126,  109,  111,  110,   24,   21,   23,  114,  105,  110,
    97,  160,  138,  160,  134,  160,    0,  160,  127,   48,
    49,   51,   62,  160,  160,  160,  160,  160,    0,  117,
    116,  110,  104,  106,   93,   96,   92,   93,    0,    0,
    85,   92,   86,   84,   91,  160,   66,   65,   76,  112,
    111,   98,  100,  101,   91,   78,   86,   76,    0,   85,
    73,   77,   70,   80,   74,   97,   96,   80,   95,   94,
    86,    0,    0,   69,   63,    0,   70,   54,    0,    0,
    
    55,    0,   62,   79,   75,    0,    0,    0,    0,   49,
    44,    0,   35,    0,   27,    0,  160,   95,   98,   51
} ;

static yyconst flex_int16_t yy_def[121] =
{   0,
    117,    1,  117,  117,  117,  117,  117,  118,  119,  117,
    117,  117,  117,  117,  117,  117,  117,  120,  120,  120,
    120,  120,  120,  120,  120,  120,  120,  120,  120,  120,
    117,  117,  117,  117,  118,  117,  119,  117,  117,  117,
    117,  117,  117,  117,  117,  117,  117,  117,  120,  120,
    120,  120,  120,  120,  120,  120,  120,  120,  120,  120,
    120,  120,  120,  120,  120,  117,  117,  117,  117,  117,
    117,  120,  120,  120,  120,  120,  120,  120,  120,  120,
    120,  120,  120,  120,  120,  117,  117,  117,  117,  117,
    120,  120,  120,  120,  120,  120,  120,  120,  120,  120,
    
    120,  120,  120,  117,  117,  120,  120,  120,  120,  120,
    120,  120,  120,  120,  120,  120,    0,  117,  117,  117
} ;

static yyconst flex_int16_t yy_nxt[206] =
{   0,
    4,    5,    6,    7,    8,    9,   10,   11,   11,   12,
    13,   14,   15,   16,   17,   18,   18,   18,   19,   18,
    20,   18,   18,   21,   18,    4,   18,   22,   23,   24,
    25,   18,   26,   18,   18,   27,   18,   28,   18,   29,
    18,   30,   18,   31,   32,   39,   40,   42,   40,   45,
    56,   59,   61,   49,   46,   43,   60,   42,   40,   41,
    57,   68,  116,   62,   58,   43,   67,   43,   69,   70,
    70,  115,   71,   86,   86,   68,   87,   43,   67,  114,
    69,  113,   88,   89,   89,  105,   90,  104,  104,  105,
    105,  112,  111,  110,   88,   35,   35,   35,   37,  109,
    
    37,  108,  107,  106,   90,   90,   87,   87,  103,  102,
    101,  100,   99,   98,   97,   96,   95,   94,   93,   92,
    91,   71,   71,   85,   84,   83,   82,   81,   80,   79,
    78,   77,   76,   75,   74,   73,   72,   41,   36,   33,
    66,   65,   64,   63,   55,   54,   53,   52,   51,   50,
    48,   47,   44,   41,   38,   36,   34,   33,  117,    3,
    117,  117,  117,  117,  117,  117,  117,  117,  117,  117,
    117,  117,  117,  117,  117,  117,  117,  117,  117,  117,
    117,  117,  117,  117,  117,  117,  117,  117,  117,  117,
    117,  117,  117,  117,  117,  117,  117,  117,  117,  117,
    
    117,  117,  117,  117,  117
} ;

static yyconst flex_int16_t yy_chk[206] =
{   0,
    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
    1,    1,    1,    1,    1,   11,   11,   13,   13,   15,
    25,   26,   27,  120,   15,   13,   26,   40,   40,   41,
    25,   42,  115,   27,   25,   40,   41,   13,   42,   43,
    43,  113,   43,   67,   67,   68,   67,   40,   41,  111,
    42,  110,   68,   69,   69,  105,   69,   88,   88,  104,
    88,  103,  101,   98,   68,  118,  118,  118,  119,   97,
    
    119,   95,   94,   91,   90,   89,   87,   86,   85,   84,
    83,   82,   81,   80,   78,   77,   76,   75,   74,   73,
    72,   71,   70,   65,   64,   63,   62,   61,   58,   57,
    56,   55,   54,   53,   52,   51,   50,   39,   35,   33,
    31,   30,   29,   28,   24,   23,   22,   21,   20,   19,
    17,   16,   14,   12,   10,    8,    7,    5,    3,  117,
    117,  117,  117,  117,  117,  117,  117,  117,  117,  117,
    117,  117,  117,  117,  117,  117,  117,  117,  117,  117,
    117,  117,  117,  117,  117,  117,  117,  117,  117,  117,
    117,  117,  117,  117,  117,  117,  117,  117,  117,  117,
    
    117,  117,  117,  117,  117
} ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lex.l"
#line 2 "lex.l"
/**
 * @file
 * Lexicographical analysis for the RevBayes language.
 *
 * @brief Lexicographical analysis using flex
 *
 * @author Fredrik Ronquist
 * @date Last modified: $Date$
 *
 * $Id$
 */

/* The following statements go into the resulting cpp code */

/* Define the call-back function for receiving input */
#define YY_INPUT rrinput

#include <cstring>

/* Hack for Windows */
#ifdef WIN32
#define strdup(a) _strdup(a)
#define fileno _fileno
#define YY_SKIP_YYWRAP
#define yywrap() 1
int isatty(int) { return 0; }
#else
extern "C" { 
    char *strdup(const char *s);
}
#define YY_SKIP_YYWRAP
#define yywrap() 1
#endif

/* Include objects needed to understand grammar.tab.h */
#include "Parser.h"     // To catch any parser debug flags
#include "RbOptions.h"
#include "RbString.h"
#include "SyntaxElement.h"
#include "SyntaxFormal.h"
#include "SyntaxFunctionCall.h"
#include "SyntaxLabeledExpr.h"

#include "grammar.tab.h"

#define YY_NEVER_INTERACTIVE 1
extern void rrinput(char *,int &,int);
#define YY_NO_UNISTD_H
#line 592 "lex.yy.cpp"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

static void yyunput (int c,char *buf_ptr  );

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
{ \
int c = '*'; \
size_t n; \
for ( n = 0; n < max_size && \
(c = getc( yyin )) != EOF && c != '\n'; ++n ) \
buf[n] = (char) c; \
if ( c == '\n' ) \
buf[n++] = (char) c; \
if ( c == EOF && ferror( yyin ) ) \
YY_FATAL_ERROR( "input in flex scanner failed" ); \
result = n; \
} \
else \
{ \
errno=0; \
while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
{ \
if( errno != EINTR) \
{ \
YY_FATAL_ERROR( "input in flex scanner failed" ); \
break; \
} \
errno=0; \
clearerr(yyin); \
} \
}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 64 "lex.l"
    
#line 747 "lex.yy.cpp"
    
	if ( !(yy_init) )
    {
		(yy_init) = 1;
        
#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif
        
		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */
            
            if ( ! yyin )
                yyin = stdin;
                
                if ( ! yyout )
                    yyout = stdout;
                    
                    if ( ! YY_CURRENT_BUFFER ) {
                        yyensure_buffer_stack ();
                        YY_CURRENT_BUFFER_LVALUE =
                        yy_create_buffer(yyin,YY_BUF_SIZE );
                    }
        
		yy_load_buffer_state( );
    }
    
	while ( 1 )		/* loops until end-of-file is reached */
    {
		yy_cp = (yy_c_buf_p);
        
		/* Support of yytext. */
		*yy_cp = (yy_hold_char);
        
		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;
        
		yy_current_state = (yy_start);
    yy_match:
		do
        {
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
            {
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
            }
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
            {
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 118 )
					yy_c = yy_meta[(unsigned int) yy_c];
                    }
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
        }
		while ( yy_base[yy_current_state] != 160 );
        
    yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
        { /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
        }
        
		YY_DO_BEFORE_ACTION;
        
    do_action:	/* This label is used only to access EOF actions. */
        
		switch ( yy_act )
        { /* beginning of action switch */
			case 0: /* must back up */
                /* undo the effects of YY_DO_BEFORE_ACTION */
                *yy_cp = (yy_hold_char);
                yy_cp = (yy_last_accepting_cpos);
                yy_current_state = (yy_last_accepting_state);
                goto yy_find_action;
                
            case 1:
                YY_RULE_SETUP
#line 65 "lex.l"
            {
                PRINTF("Flex found 'function'\n");
                return FUNCTION;
            }
                YY_BREAK
            case 2:
                YY_RULE_SETUP
#line 69 "lex.l"
            {
                PRINTF("Flex found 'class'\n");
                return CLASS;
            }
                YY_BREAK
            case 3:
                YY_RULE_SETUP
#line 73 "lex.l"
            {
                PRINTF("Flex found 'for'\n");
                return FOR;
            }
                YY_BREAK
            case 4:
                YY_RULE_SETUP
#line 77 "lex.l"
            {
                PRINTF("Flex found 'in'\n");
                return IN;
            }
                YY_BREAK
            case 5:
                YY_RULE_SETUP
#line 81 "lex.l"
            {
                PRINTF("Flex found 'if'\n");
                return IF;
            }
                YY_BREAK
            case 6:
                YY_RULE_SETUP
#line 85 "lex.l"
            {
                PRINTF("Flex found 'else'\n");
                return ELSE;
            }
                YY_BREAK
            case 7:
                YY_RULE_SETUP
#line 89 "lex.l"
            {
                PRINTF("Flex found 'while'\n");
                return WHILE;
            }
                YY_BREAK
            case 8:
                YY_RULE_SETUP
#line 93 "lex.l"
            {
                PRINTF("Flex found 'next'\n");
                return NEXT;
            }
                YY_BREAK
            case 9:
                YY_RULE_SETUP
#line 97 "lex.l"
            {
                PRINTF("Flex found 'break'\n");
                return BREAK;
            }
                YY_BREAK
            case 10:
                YY_RULE_SETUP
#line 101 "lex.l"
            {
                PRINTF("Flex found 'return'\n");
                return RETURN;
            }
                YY_BREAK
            case 11:
                YY_RULE_SETUP
#line 105 "lex.l"
            {
                PRINTF("Flex found 'null'\n");
                return RBNULL;
            }
                YY_BREAK
            case 12:
                YY_RULE_SETUP
#line 109 "lex.l"
            {
                PRINTF("Flex found 'false'\n");
                return FALSE;
            }
                YY_BREAK
            case 13:
                YY_RULE_SETUP
#line 113 "lex.l"
            {
                PRINTF("Flex found 'true'\n");
                return TRUE;
            }
                YY_BREAK
            case 14:
                YY_RULE_SETUP
#line 117 "lex.l"
            {
                PRINTF("Flex found 'NULL'\n");
                return RBNULL;
            }
                YY_BREAK
            case 15:
                YY_RULE_SETUP
#line 121 "lex.l"
            {
                PRINTF("Flex found 'FALSE'\n");
                return FALSE;
            }
                YY_BREAK
            case 16:
                YY_RULE_SETUP
#line 125 "lex.l"
            {
                PRINTF("Flex found 'TRUE'\n");
                return TRUE;
            }
                YY_BREAK
            case 17:
                YY_RULE_SETUP
#line 129 "lex.l"
            {
                PRINTF("Flex found real %s -- ", yytext);
                yylval.realValue = strtod(yytext,NULL); 
                PRINTF("double value = %f\n",yylval.realValue);
                return REAL;
            }
                YY_BREAK
            case 18:
                YY_RULE_SETUP
#line 135 "lex.l"
            {
                PRINTF("Flex found real %s -- ", yytext);
                yylval.realValue = strtod(yytext,NULL); 
                PRINTF("double value = %f\n",yylval.realValue);
                return REAL;
            }
                YY_BREAK
            case 19:
                YY_RULE_SETUP
#line 141 "lex.l"
            { 
                /* Treat ints with exponents as floating point values */
                PRINTF("Flex found int with exponent %s -- ", yytext);
                yylval.realValue = strtod(yytext,NULL); 
                PRINTF("double value = %f\n",yylval.realValue);
                return REAL;
            }
                YY_BREAK
            case 20:
                YY_RULE_SETUP
#line 148 "lex.l"
            {
                PRINTF("Flex found int %s -- ", yytext);
                yylval.intValue = int( strtol(yytext,NULL,10) ); 
                PRINTF("int value = %d\n",yylval.intValue);
                return INT;
            }
                YY_BREAK
            case 21:
                YY_RULE_SETUP
#line 154 "lex.l"
            {
                PRINTF("Flex found id (name) %s -- ", yytext);
                yylval.string = yytext;
                PRINTF("string value = %s\n", yylval.string);
                return NAME;
            }
                YY_BREAK
            case 22:
                /* rule 22 can match eol */
                YY_RULE_SETUP
#line 160 "lex.l"
            {
                PRINTF("Flex found string %s -- ", yytext); 
                /* Strip quotes from string */
                yytext[strlen(yytext)-1] = '\0';
                yylval.string = yytext + 1;
                PRINTF("string value = %s\n", yylval.string);
                return STRING;
            }
                YY_BREAK
            case 23:
                YY_RULE_SETUP
#line 168 "lex.l"
            {
                PRINTF("Flex found comment %s\n", yytext);
                return COMMENT;
            }
                YY_BREAK
            case 24:
                YY_RULE_SETUP
#line 172 "lex.l"
            {
                PRINTF("Flex found '<-'\n");
                return ARROW_ASSIGN;
            }
                YY_BREAK
            case 25:
                YY_RULE_SETUP
#line 176 "lex.l"
            {
                PRINTF("Flex found ':='\n");
                return EQUATION_ASSIGN;
            }
                YY_BREAK
            case 26:
                YY_RULE_SETUP
#line 180 "lex.l"
            {
                PRINTF("Flex found '~'\n");
                return TILDE_ASSIGN;
            }
                YY_BREAK
            case 27:
                YY_RULE_SETUP
#line 184 "lex.l"
            {
                PRINTF("Flex found '='\n");
                return EQUAL;
            }
                YY_BREAK
            case 28:
                YY_RULE_SETUP
#line 188 "lex.l"
            {
                PRINTF("Flex found '&'\n");
                return AND;
            }
                YY_BREAK
            case 29:
                YY_RULE_SETUP
#line 192 "lex.l"
            {
                PRINTF("Flex found '|'\n");
                return OR;
            }
                YY_BREAK
            case 30:
                YY_RULE_SETUP
#line 196 "lex.l"
            {
                PRINTF("Flex found '&&'\n");
                return AND;
            }
                YY_BREAK
            case 31:
                YY_RULE_SETUP
#line 200 "lex.l"
            {
                PRINTF("Flex found '||'\n");
                return OR;
            }
                YY_BREAK
            case 32:
                YY_RULE_SETUP
#line 204 "lex.l"
            {
                PRINTF("Flex found '>'\n");
                return GT;
            }
                YY_BREAK
            case 33:
                YY_RULE_SETUP
#line 208 "lex.l"
            {
                PRINTF("Flex found '>='\n");
                return GE;
            }
                YY_BREAK
            case 34:
                YY_RULE_SETUP
#line 212 "lex.l"
            {
                PRINTF("Flex found '<'\n");
                return LT;
            }
                YY_BREAK
            case 35:
                YY_RULE_SETUP
#line 216 "lex.l"
            {
                PRINTF("Flex found '<='\n");
                return LE;
            }
                YY_BREAK
            case 36:
                YY_RULE_SETUP
#line 220 "lex.l"
            {
                PRINTF("Flex found '=='\n");
                return EQ;
            }
                YY_BREAK
            case 37:
                YY_RULE_SETUP
#line 224 "lex.l"
            {
                PRINTF("Flex found '!='\n");
                return EQ;
            }
                YY_BREAK
            case 38:
                YY_RULE_SETUP
#line 228 "lex.l"
            {
                PRINTF ("Flex found white space\n");
                /* Ignore white space */
            }
                YY_BREAK
            case 39:
                /* rule 39 can match eol */
                YY_RULE_SETUP
#line 232 "lex.l"
            {
                PRINTF ("Flex found newline\n");
                foundNewline = true;
                return yytext[0];
            }
                YY_BREAK
            case 40:
                YY_RULE_SETUP
#line 237 "lex.l"
            {
                /* any character not matching existing rules */
                /* pass it onto the parser and let the parser handle it */
                PRINTF("Flex found char 0x%X ('%c')\n", yytext[0], yytext[0]);
                return yytext[0];
            }
                YY_BREAK
            case 41:
                YY_RULE_SETUP
#line 243 "lex.l"
                ECHO;
                YY_BREAK
#line 1175 "lex.yy.cpp"
            case YY_STATE_EOF(INITIAL):
                yyterminate();
                
            case YY_END_OF_BUFFER:
            {
                /* Amount of text matched not including the EOB char. */
                int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;
                
                /* Undo the effects of YY_DO_BEFORE_ACTION. */
                *yy_cp = (yy_hold_char);
                YY_RESTORE_YY_MORE_OFFSET
                
                if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
                {
                    /* We're scanning a new file or input source.  It's
                     * possible that this happened because the user
                     * just pointed yyin at a new source and called
                     * yylex().  If so, then we have to assure
                     * consistency between YY_CURRENT_BUFFER and our
                     * globals.  Here is the right place to do so, because
                     * this is the first action (other than possibly a
                     * back-up) that will match for the new input source.
                     */
                    (yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
                    YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
                    YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
                }
                
                /* Note that here we test for yy_c_buf_p "<=" to the position
                 * of the first EOB in the buffer, since yy_c_buf_p will
                 * already have been incremented past the NUL character
                 * (since all states make transitions on EOB to the
                 * end-of-buffer state).  Contrast this with the test
                 * in input().
                 */
                if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
                { /* This was really a NUL. */
                    yy_state_type yy_next_state;
                    
                    (yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;
                    
                    yy_current_state = yy_get_previous_state(  );
                    
                    /* Okay, we're now positioned to make the NUL
                     * transition.  We couldn't have
                     * yy_get_previous_state() go ahead and do it
                     * for us because it doesn't know how to deal
                     * with the possibility of jamming (and we don't
                     * want to build jamming into it because then it
                     * will run more slowly).
                     */
                    
                    yy_next_state = yy_try_NUL_trans( yy_current_state );
                    
                    yy_bp = (yytext_ptr) + YY_MORE_ADJ;
                    
                    if ( yy_next_state )
                    {
                        /* Consume the NUL. */
                        yy_cp = ++(yy_c_buf_p);
                        yy_current_state = yy_next_state;
                        goto yy_match;
                    }
                    
                    else
                    {
                        yy_cp = (yy_c_buf_p);
                        goto yy_find_action;
                    }
                }
                
                else switch ( yy_get_next_buffer(  ) )
                {
                    case EOB_ACT_END_OF_FILE:
                    {
                        (yy_did_buffer_switch_on_eof) = 0;
                        
                        if ( yywrap( ) )
                        {
                            /* Note: because we've taken care in
                             * yy_get_next_buffer() to have set up
                             * yytext, we can now set up
                             * yy_c_buf_p so that if some total
                             * hoser (like flex itself) wants to
                             * call the scanner after we return the
                             * YY_NULL, it'll still work - another
                             * YY_NULL will get returned.
                             */
                            (yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;
                            
                            yy_act = YY_STATE_EOF(YY_START);
                            goto do_action;
                        }
                        
                        else
                        {
                            if ( ! (yy_did_buffer_switch_on_eof) )
                                YY_NEW_FILE;
                        }
                        break;
                    }
                        
                    case EOB_ACT_CONTINUE_SCAN:
                        (yy_c_buf_p) =
                        (yytext_ptr) + yy_amount_of_matched_text;
                        
                        yy_current_state = yy_get_previous_state(  );
                        
                        yy_cp = (yy_c_buf_p);
                        yy_bp = (yytext_ptr) + YY_MORE_ADJ;
                        goto yy_match;
                        
                    case EOB_ACT_LAST_MATCH:
                        (yy_c_buf_p) =
                        &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];
                        
                        yy_current_state = yy_get_previous_state(  );
                        
                        yy_cp = (yy_c_buf_p);
                        yy_bp = (yytext_ptr) + YY_MORE_ADJ;
                        goto yy_find_action;
                }
                break;
            }
                
            default:
                YY_FATAL_ERROR(
                               "fatal flex scanner internal error--no action found" );
        } /* end of action switch */
    } /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;
    
	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
                       "fatal flex scanner internal error--end of buffer missed" );
    
	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
    { /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
        {
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
        }
        
		else
        {
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
        }
    }
    
	/* Try to read more data. */
    
	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;
    
	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);
    
	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
    /* don't do the read, it's not guaranteed to return an EOF,
     * just force an EOF
     */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;
    
	else
    {
        int num_to_read =
        YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;
        
		while ( num_to_read <= 0 )
        { /* Not enough room in the buffer - grow it. */
            
			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;
            
			int yy_c_buf_p_offset =
            (int) ((yy_c_buf_p) - b->yy_ch_buf);
            
			if ( b->yy_is_our_buffer )
            {
				int new_size = b->yy_buf_size * 2;
                
				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;
                
				b->yy_ch_buf = (char *)
                /* Include room in for 2 EOB chars. */
                yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
            }
			else
            /* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;
            
			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
                               "fatal error - scanner input buffer overflow" );
            
			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];
            
			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
            number_to_move - 1;
            
        }
        
		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;
        
		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
                 (yy_n_chars), num_to_read );
        
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
    }
    
	if ( (yy_n_chars) == 0 )
    {
		if ( number_to_move == YY_MORE_ADJ )
        {
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
        }
        
		else
        {
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
            YY_BUFFER_EOF_PENDING;
        }
    }
    
	else
		ret_val = EOB_ACT_CONTINUE_SCAN;
    
	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;
    
	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];
    
	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);
    
	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
    {
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
        {
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
        }
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
        {
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 118 )
				yy_c = yy_meta[(unsigned int) yy_c];
        }
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
    }
    
	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    register char *yy_cp = (yy_c_buf_p);
    
	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
    {
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
    }
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
    {
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 118 )
			yy_c = yy_meta[(unsigned int) yy_c];
    }
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 117);
    
	return yy_is_jam ? 0 : yy_current_state;
}

static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);
    
	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);
    
	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
    { /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
                                                                   YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
        &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];
        
		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;
        
		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
        (yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;
        
		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
    }
    
	*--yy_cp = (char) c;
    
	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput (void)
#else
static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);
    
	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
    {
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
        /* This was really a NUL. */
			*(yy_c_buf_p) = '\0';
        
		else
        { /* need more input */
			int offset = int( (yy_c_buf_p) - (yytext_ptr) );
			++(yy_c_buf_p);
            
			switch ( yy_get_next_buffer(  ) )
            {
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */
                    
					/* Reset buffer status. */
					yyrestart(yyin );
                    
					/*FALLTHROUGH*/
                    
				case EOB_ACT_END_OF_FILE:
                {
					if ( yywrap( ) )
						return 0;
                    
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
                }
                    
				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
            }
        }
    }
    
	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);
    
	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
        yy_create_buffer(yyin,YY_BUF_SIZE );
	}
    
	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;
    
	if ( YY_CURRENT_BUFFER )
    {
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
    }
    
	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );
    
	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    (yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );
    
	b->yy_buf_size = size;
    
	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );
    
	b->yy_is_our_buffer = 1;
    
	yy_init_buffer(b,file );
    
	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;
    
	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;
    
	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );
    
	yyfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );
    
	b->yy_input_file = file;
	b->yy_fill_buffer = 1;
    
    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }
    
    b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    if ( ! b )
		return;
    
	b->yy_n_chars = 0;
    
	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;
    
	b->yy_buf_pos = &b->yy_ch_buf[0];
    
	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;
    
	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    if (new_buffer == NULL)
		return;
    
	yyensure_buffer_stack();
    
	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
    {
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
    }
    
	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;
    
	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    if (!YY_CURRENT_BUFFER)
		return;
    
	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);
    
	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {
        
		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
        (num_to_alloc * sizeof(struct yy_buffer_state*)
         );
		
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
        
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}
    
	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){
        
		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;
        
		num_to_alloc = int( (yy_buffer_stack_max) + grow_size );
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
        ((yy_buffer_stack),
         num_to_alloc * sizeof(struct yy_buffer_state*)
         );
        
		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
        base[size-2] != YY_END_OF_BUFFER_CHAR ||
        base[size-1] != YY_END_OF_BUFFER_CHAR )
    /* They forgot to leave room for the EOB's. */
		return 0;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );
    
	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;
    
	yy_switch_to_buffer(b  );
    
	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param str a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes( yystr,int( strlen(yystr) ) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param bytes the byte buffer to scan
 * @param len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );
    
	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];
    
	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;
    
	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );
    
	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;
    
	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    (void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
do \
{ \
/* Undo effects of setting up yytext. */ \
int yyless_macro_arg = (n); \
YY_LESS_LINENO(yyless_macro_arg);\
yytext[yyleng] = (yy_hold_char); \
(yy_c_buf_p) = yytext + yyless_macro_arg; \
(yy_hold_char) = *(yy_c_buf_p); \
*(yy_c_buf_p) = '\0'; \
yyleng = yyless_macro_arg; \
} \
while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
    return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
    return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
    return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
    return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
    yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
    yyout = out_str ;
}

int yyget_debug  (void)
{
    return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
    yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
    /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */
    
    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;
    
    /* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif
    
    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}
    
	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;
    
    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );
    
    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;
    
	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 243 "lex.l"



