/* This file is automatically generated at installation by regenerate.sh script */

static const char* INSTALL_DIR = "/home/johadunf/dev/project/revBayes/code/rb-2014-03-25/revbayes-code-git/projects/cmake";
static const char* HELP_DIR = "/home/johadunf/dev/project/revBayes/code/rb-2014-03-25/revbayes-code-git/help";
