/* This file is automatically generated at installation by regenerate.sh script */

static const char* INSTALL_DIR = "/Users/mlandis/Documents/code/revbayes-code/projects/cmake";
static const char* HELP_DIR = "/Users/mlandis/Documents/code/revbayes-code/help";
