/* This file is automatically generated at installation by regenerate.sh script */

static const char* INSTALL_DIR = "/Users/chi/Research/RevBayes/projects/cmake";
static const char* HELP_DIR = "/Users/chi/Research/RevBayes/help";
